version: '3'
services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - JWT_SIGNING_KEY=secret
    depends_on:
      - temporal
  temporal:
    image: temporalio/auto-setup:1.21
    ports:
      - "7233:7233"
